### ISSUE TITLE
Add buttons

### ISSUE THREAD

**Issue by JacobSchoolAcc2024** [JacobSchoolAcc2024/Idle_Gym#4]
Buttons for users to click e.g. push ups

**Comment by prrajput1199** [comment]
Hey, I want to work on this! I will add buttons for different kinds of exercises and some CSS, okay?

Feel free to let me know if you need any further adjustments!

**Comment by JacobSchoolAcc2024** [comment]
Hello, this is a school project so sadly I am not able to allow external
from. Thank you for trying to contribute though.
